### ISSUE TITLE
Http\Controllers\ArrayIterator' not found

### ISSUE THREAD

**Issue by jamilalidrus** [bborrel/google-scholar-profile-parser#2]
Http\Controllers\ArrayIterator' not found

**Comment by bborrel** [comment]
@jamilalidrus Since you didn't provide any details about which code resulted in this error, at this point I can only suppose that you wrote erroneous code. Have you checked the [example code](https://github.com/bborrel/google-scholar-profile-parser/blob/master/doc/example-publications.php) to fetch a scholar's publications?

Also, the class [ArrayIterator](https://www.php.net/manual/en/class.arrayiterator.php) used in the example code is the one from Standard PHP Library (SPL). So if your code is like the example code, you shouldn't get this error message. The prefix 'Http\Controllers\' in the error message indicates that your code is trying to use the class ArrayIterator declared in Http\Controllers, which doesn't exist, hence the 'not found' error message.

**Comment by bborrel** [comment]
Closing because didn't receive any reply.
